---
title: "Assignment 8"
author: "Andy Atallah"
date: "2023-01-26"
output: html_document
---
## Code Reflection: Weekly Assignment 2
```{r}
# The original code that I submitted for Weekly Assignment 2
dfFunction <- function(mean1=NULL, mean2=NULL){
  Type <- rep(c("Control", "Treatment"), each=25)
  Value <- c(rnorm(25, mean=10, sd=1.5), rnorm(25, mean=45, sd=2))
  return(data.frame(Type, Value, stringsAsFactors = F))
}

dfOutput <- dfFunction()
head(dfFunction())
head(dfFunction(mean1=100, mean2=1))
# The function runs with new inputs for mean1 and mean2, but without referencing mean1 and mean2 in the body of the function, I do not think the data is as we would want it to be. For example, it does not seem as though the beginning values have changed to have a mean of 100 in the table above despite changing mean1 to 100. I could change the function by including mean1 and mean2 as variables in the definition of Value, as the solution did.
```
```{r}
dfFunctionNew <- function(mean1=10, mean2=45){ #adding mean1 and mean2 to align with solution
  Type <- rep(c("Control", "Treatment"), each=25)
  Value <- c(rnorm(25, mean=mean1, sd=1.5), rnorm(25, mean=mean2, sd=2))
  dFrame <- data.frame(Type, Value, stringsAsFactors = F)
  return(dFrame)
}

dfOutputNew <- dfFunctionNew()
head(dfOutputNew)

head(dfFunctionNew(mean1=100, mean2=1)) #Testing with new means
# These values appear to have changed compared to the values generated by the new mean1 and mean2 for my original code. I would suspect that the function is now able to work with new means with this change.
```
## Code Reflection: Assignment 6
```{r}
library(tidyverse)
# I had the tibble (2x4) generated by the code in the first part of the solution to Question 8, but I did not have additional code to generate the 2x5 tibble shown at the end of the question.
irisFinal <- iris %>%
  filter(Species == "virginica"| Species == "versicolor", Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Sepal.Length, Sepal.Width, Species) %>%
  arrange(by=desc(Sepal.Length)) %>%
  mutate(Sepal.Area=Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarize(meanSepalLength = mean(Sepal.Length), meanSepalWidth = mean(Sepal.Width), TotalNumber =n())

print(irisFinal)
# In order to change this code to match the solution, I will have to add mean sepal area to the summary table and arrange by this variable at the end of the piping structure.
irisFinal2 <- iris %>%
  filter(Species == "virginica"| Species == "versicolor", Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Sepal.Length, Sepal.Width, Species) %>%
  mutate(Sepal.Area=Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarize(meanSepalLength = mean(Sepal.Length), meanSepalWidth = mean(Sepal.Width), meanSepalArea = mean(Sepal.Area), TotalNumber=n()) %>%
   arrange(desc(meanSepalArea))

print(irisFinal2)
```
## Code annotation
```{r}
library(tidyverse)
library(ggthemes)

dryad = read.table(file="Data/Veysey-Babbitt_data_amphibians.csv", header=T, sep=",")
table(dryad$species) #allows you to see different groups of character column
summary(dryad$mean.hydro) #min, quartile, med, mean, max

dryad$species<-factor(dryad$species, labels=c("Spotted Salamander", "Wood Frog")) #creating 'labels' to use for the plot

class(dryad$treatment)

dryad$treatment <- factor(dryad$treatment, 
                              levels=c("Reference",
                                       "100m", "30m")) #sets groups to be compared
p<- ggplot(data=dryad, #use data from the dryad dataset
           aes(x=interaction(wetland, treatment), #group treatment and wetland
               y=count.total.adults, fill=factor(year))) + geom_bar(position="dodge", stat="identity", color="black") + #use count.total.adults for y variable; fill color based on year; create bar graph with different years as different bars next to one another instead of being one stack for each x axis break
  ylab("Number of breeding adults") + #use this as the y label
  xlab("") + #do not have a normal x axis label
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) + #y axis should be broken up by 100s
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) + #x axis should have these particular values, which are not equal distance apart
  facet_wrap(~species, nrow=2, strip.position="right") + #make two strips so that one of the plots is on top of the other; have two rows; display the labels to the right
  theme_few() + scale_fill_grey() + #use this theme and use grayscale for the bars
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), legend.position="top",  legend.title= element_blank(), axis.title.y = element_text(size=12, face="bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) + #use gray for the background and black for the outline; place year legend at top of graph; do not have a title for the legend; set formatting for the y axis title; set vertical labels on the right for species
  guides(fill=guide_legend(nrow=1,byrow=TRUE)) #make the legend be one row 

p
```



