---
title: "Assignment3"
author: "Andy Atallah"
date: "2023-01-12"
output: html_document
---
## Question 1
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

z <- x^a^b
"Output: 3.61714"

z <- (x^a)^b
"Output: 1.997611"

z <- 3*x^3 + 2*x^2 + 1
"Output: 7.413"
```

## Question 2
```{r}
z <- c(seq(from=1, to=8), seq(from=7, to=1))
"Output: 1 2 3 4 5 6 7 8 7 6 5 4 3 2 1"

z <- rep(x=1:5, c(1, 2, 3, 4, 5))
"Output: 1 2 2 3 3 3 4 4 4 4 5 5 5 5 5"

z <- rep(x=5:1, c(1, 2, 3, 4, 5))
"Output: 5 4 4 3 3 3 2 2 2 2 1 1 1 1 1"
```

## Question 3
```{r}
queue <- c("sheep", "fox", "owl", "ant")

queue <- c(queue[1:4], "serpent")
"Output: sheep   fox     owl     ant     serpent"

queue <- queue[2:5]
"Output: fox     owl     ant     serpent"

queue[1] <- "donkey"
"Output: donkey  fox     owl     ant     serpent"

queue <- queue[1:4]
"Output: donkey fox    owl    ant"

append(queue, "aphid", after=4)
"Output: donkey fox    owl    ant    aphid"

queue <- c(queue[1:4], "aphid")
queue <- c(F, F, F, F, T)
which(queue)
```

